Add documentation on API page refs #6
occitech/zoupam pull request #16
Opened 2017-01-18 11:24 UTC by Porygoon

Documantation was added on the page where we add our own Redmine/Toggl APIKey

2017-01-18 11:29 UTC, real34 commented
Il manque les liens sur les urls !

2017-01-18 12:46 UTC, real34 commented on src/Main.elm
> +        , div [] [text "Votre clé Toggl est accessible depuis ce lien: https://toggl.com/app/profile"]
Pour ajouter un lien ici, il te faut un sous élément (identique au `div [] [ h1 [] .... ]` du dessus)

2017-01-18 12:46 UTC, real34 commented on src/Configurator.elm
>              |> ConfigInput.view (UpdateConfig togglKey)
L'aide pourrait être insérée au niveau de chaque configuration, plutôt que dans un bloc en fin de configuration.

Ainsi cela serait un paramètre additionnel à `ConfigInput.view`

2017-01-18 17:01 UTC, adrien-louis-r commented on src/Main.elm
> +        , h2 [] [text "Où trouver vos clé API ?"]
J'aurais plutôt mis cette aide au niveau du "Configurator"

2017-01-19 10:22 UTC, real34 approved these changes
Bien joué !

2017-01-19 10:22 UTC, real34 commented on src/Configurator.elm
> +            |> ConfigInput.view (UpdateConfig redmineKey) (helpRedmineAPI)
Maintenant que c'est extrait, les parenthèses ne sont plus nécessaires

2017-01-19 10:22 UTC, real34 commented on src/Configurator.elm
> +            |> ConfigInput.view (UpdateConfig togglKey) (helpTogglAPI)
Idem ici

2017-01-19 10:22 UTC, real34 commented on src/Views/ConfigInput.elm
> +        , helpAPI
Chipotage : ça serait plutôt `helpText`

2017-01-19 10:27 UTC, bchellet commented
Non validé car : 
- Texte pas clair avec faute d'orthographe et manque de ponctuation.
Texte incriminé :
"Votre clé Redmine est accessible depuis ce lien pour obtenir votré clé il suffit de cliquer sur 'Afficher' en dessous de 'Clé d'accès API'"

- Rendre le texte plus sympa à lire. Il est collé à la liste, ce n'est pas facilement lisible.

2017-01-19 13:01 UTC, real34 requested changes
S'il était possible de nettoyer un minimum (< 5 min) ça serait bien, pour éviter d'introduire de la dette technique dès cette première feature !

2017-01-19 13:01 UTC, real34 commented on src/Configurator.elm
> +helpRedmineAPI = i [class "br"] [text "Votre clé API Redmine est accessible depuis "
Mieux vaudrait remplacer le `i` par un `p` au lieu de ce hackavec la classe `br`  ...

@JulienPradet va nous faire une crise cardiaque :)

2017-01-19 13:01 UTC, real34 commented on src/Configurator.elm
> +       , text ", pour obtenir votre clée il suffit de cliquer sur 'Afficher' en dessous de 'Clé d'accès API' (qui se situe à droite de l'écran)."]
s/clée/clé/

2017-01-19 13:01 UTC, real34 commented on src/main.css
> +  display: block;
Ne serait plus nécessaire du coup

2017-01-19 16:19 UTC, bchellet commented
Non validé :

- Manque un espace sur le côté gauche. Le texte touche le bord de l'écran.
- "Clée" est une faute

2017-01-19 17:10 UTC, real34 requested changes

2017-01-19 17:10 UTC, real34 commented on src/Configurator.elm
> +helpRedmineAPI = p [class "br"] [text "Votre clé API Redmine est accessible depuis "
`class "br"` à supprimer stp

2017-01-20 08:52 UTC, real34 approved these changes
merci !

2017-01-20 08:55 UTC, merged