Add some useful information
occitech/zoupam pull request #18
Opened 2017-01-25 09:53 UTC by Porygoon

Realisation of the issue #12

2017-01-25 10:07 UTC, real34 requested changes
La conversion est faite à plusieurs endroits et je pense qu'il y a moyen de rendre ça encore plus lisible et de supprimer beaucoup de code. Cf mes commentaires

2017-01-25 10:07 UTC, real34 commented on src/Views/Versions.elm
> +                    List.foldr (\timeEntry acc -> acc + (toFloat (timeEntry.duration) / 60 / 60 / 1000)) 0 entries
Il serait bien d'extraire cette conversion `toFloat (timeEntry.duration) / 60 / 60 / 1000)` dans une fonction qui faciliterait la ecture du code.

Exemple : `msToHours : Int -> Float`

2017-01-25 10:07 UTC, real34 commented on src/Views/Versions.elm
> +            acc + (toFloat (timeEntry.duration) / 60 / 60 / 1000) |> convertIntoDay
Duplication de la conversion du temps, utiliser la même fonction que proposé plus tôt la supprimerait

2017-01-25 10:07 UTC, real34 commented on src/Views/Versions.elm
> +            acc + 0
directement `acc` du coup

2017-01-25 10:07 UTC, real34 commented on src/Views/Versions.elm
> +            acc + (toFloat (timeEntry.duration) / 60 / 60 / 1000) |> convertIntoDay
Et du coup y a-t-il un besoin d'avoir encore des heures ? Je ne pense pas, et cela permettrait d'avoir directement un truc du genre : `acc + (timeEntry.duration |> msToDays)`

D'ailleurs, en l'état es-tu sûr que ce n'est pas `acc + duration` qui est converti en `convertIntoDay` ? (ma méconnaissance de Elm me joue peut-être un tour)

2017-01-25 10:07 UTC, real34 commented on src/Views/Versions.elm
> +convertIntoDay decTime =
`hours` serait plus explicite que `decTime` amha, et en soit la méthode ne dit pas trop "ce qui" est converti en jours

2017-01-25 10:07 UTC, real34 commented on src/Views/Versions.elm
> +capitalCalculator estimated realisated billableTime =
Je ne crois pas que `relaisated` existe en anglais :nerd_face: 

Propositions: `actual`, `realised`, `spent`

2017-01-25 10:07 UTC, real34 commented on src/Views/Versions.elm
> +                    List.foldr billableAccumulator 0 entries
Plutôt que de faire un `billableAccumulator` je me demande si on ne ferait pas mieux ici de filtrer les `entries` en amont.

Un truc du genre `List.foldr timeAccumulator 0 (List.filter isBillable entries)` 
... syntaxe à améliorer par @adrien-louis-r  qui saura sans doute mieux comment cela s'écrirait

2017-01-25 10:10 UTC, adrien-louis-r commented on src/Views/Versions.elm
> +                    List.foldr billableAccumulator 0 entries
`entries |> List.filter isBillable |> List.foldr timeAccumulator 0` tout simplement ?

2017-01-25 10:11 UTC, adrien-louis-r commented on src/Views/Versions.elm
> +            , td [] [ issue.doneRatio |> Debug.log "ratio" |> toString |> text]
N'oublie de supprimer les debugs non utilisés

2017-01-25 10:13 UTC, aloross reviewed
Pierre a dis le principal, il faut éviter la duplication en créant des fonctions.

2017-01-25 11:00 UTC, Porygoon commented on src/Views/Versions.elm
> +                    List.foldr billableAccumulator 0 entries
Je préférerais laisser le billableAccumulator, c'est plus lisible je trouve :/

2017-01-25 13:01 UTC, JulienPradet commented on src/Views/Versions.elm
> +                    List.foldr billableAccumulator 0 entries
L'avantage en lecture de l'écriture d'adrien même si elle n'est pas "toute simple" (:p) c'est que le filtre est clair et que la lecture de l'acumulateur aussi.

Avec ton billableAccumulator il faut bien comprendre ton case pour comprendre que tu fais un filtre.
Cela dit, si c'est la ligne 91 que tu veux rendre plus claire, tu peux faire une fonction 'computeBillableAmount' qui fera ce qu'à dit adrien. Comme ca tu gardes la lisibilté à cette ligne là, et tu gardes la lisibilté dans ton calcul aussi.

2017-01-27 13:06 UTC, real34 approved these changes

2017-01-27 13:06 UTC, real34 commented on src/Views/Versions.elm
> +            , td [] [ text (roundedAtTwoDigitAfterComma (timeLeftCalculator estimated billableTime)) ]
Il faudra un jour essayer d'homogénéïser l'utilisation de `|>` ou non, car là ça fait un peu bizarre d'avoir des différences selon les lignes

```
billableTime |> roundedAtTwoDigitAfterComma |> text
(timeLeftCalculator estimated billableTime) |> roundedAtTwoDigitAfterComma |> text
```

2017-01-27 14:08 UTC, aloross approved these changes

2017-01-27 15:17 UTC, bchellet commented
Concernant : les informations suivantes doivent être triées par priorité.
>> Anomalie 1 : ce n’est pas le cas. La tache 9579 à une priorité haute et elle est en avant dernière position au lieu de la première

>> Anomalie 2 : le temps estimé ne doit pas afficher plus de 2 chiffres après la virgule (ex 0.83 au lieu de 0.833333)

>> Anomalie 3 : le temps facturable est incorrect, on a des valeurs de l’ordre de 0.06, ce qui ne correspond pas aux temps toggl

>> Anomalie 4 : Le capital n’est pas bon (on a une valeur égale à Infinity par exemple)

>> Anomalie 5 : le temps restant est toujours égale à 0 cela semble bizarre quand une tache est en cours et que sont temps consommé est inférieur à l'estimation

2017-01-27 16:34 UTC, bchellet commented
1- L'ordre des priorités n'est pas Ok 
2- Les valeurs de la colonne capital non plus. On a des Infinity.00 et des NaN.00
3- Les liens vers les tickets Redmine ne sont pas Ok. Ils ne mènent pas vers le ticket (anomalie non comprise dans le besoin initial mais à faire)

2017-02-03 12:58 UTC, real34 approved these changes

2017-02-03 12:58 UTC, real34 commented on src/Views/Versions.elm
> +            , td [] [ billableTime |> formatTime |> text ]
:+1: bien joué

2017-02-03 13:01 UTC, adrien-louis-r commented on src/Views/Versions.elm
> +    Round.round 2 ((ms / 60 / 60 / 1000) / 6)
Attention à la duplication, tu peux utiliser les fonctions `msToDays` et `roundedAtTwoDigitAfterComma` ici.

2017-02-03 13:01 UTC, adrien-louis-r commented on src/Views/Versions.elm
> +      else
Indentation inconsitante.

2017-02-03 13:04 UTC, adrien-louis-r commented on src/Views/Versions.elm
> +       (estimated  |> daysToMs) - ((100 * (billableTime)) / toFloat (realised)) |> Just
Par convention, on laisse une ligne vide à la fin des fichiers, ça doit être une configuration dans ton IDE.

2017-02-03 13:05 UTC, Porygoon commented on src/Views/Versions.elm
> +    Round.round 2 ((ms / 60 / 60 / 1000) / 6)
J'ai pas compris

2017-02-03 13:05 UTC, aloross requested changes
Une belle duplication à corriger.

2017-02-03 13:06 UTC, Porygoon commented on src/Views/Versions.elm
> +       (estimated  |> daysToMs) - ((100 * (billableTime)) / toFloat (realised)) |> Just
Ah bon ?
Justement moi je l'enlève ça me stresse

2017-02-03 13:35 UTC, aloross approved these changes

2017-02-03 14:05 UTC, merged